### ISSUE TITLE
Adjust volume inverse proportionally to the frequence

### ISSUE THREAD

**Issue by sunyatasattva** [sunyatasattva/overtones#7]
High frequencies tend to sound very loud

**Comment by sunyatasattva** [comment]
https://en.wikipedia.org/wiki/A-weighting

**Comment by meszaros-lajos-gyorgy** [comment]
Can something similar be done with different wave shapes? A sawtooth and a square wave sounds significantly louder compared to sine or triangle waves.

**Comment by sunyatasattva** [comment]
It definitely can be implemented regardless of wave shape. I have implemented a function of my own making based on what I have learned from the link above, as it was not exactly what I was looking for.

I am not 100% pleased with the function, yet, but you can try and see if it fits your use case. I plan to extract my sound generation library from this project as a standalone library. I had planned that since the beginning, actually, but I think it's still not quite ready for prime time.

If you want to use that, I can speed up the extracting process, and maybe we can collaborate on that repo to fix the last few things I thought needed fixing (there was something annoying happening with Firefox, specifically).

**Comment by meszaros-lajos-gyorgy** [comment]
That is the exact same reason why I have the monochord-core repo, but I had little time to progress with that. We could compare our solutions in the future, when we make some progress. So I guess the extraction can wait, until you add all, what you plan to add to 2.0
